
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Jan 10 15:27:25 CET 2022
//----------------------------------------------------

package de.unitrier.st.uap;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int STARTCB = 11;
  public static final int AND = 22;
  public static final int LT = 18;
  public static final int ELSE = 6;
  public static final int PLUS = 24;
  public static final int OR = 23;
  public static final int THEN = 5;
  public static final int SEMI = 13;
  public static final int IN = 3;
  public static final int WHILE = 7;
  public static final int ENDCB = 12;
  public static final int TRUE = 30;
  public static final int STARTBR = 9;
  public static final int IF = 4;
  public static final int GT = 19;
  public static final int ID = 28;
  public static final int LOE = 21;
  public static final int DO = 8;
  public static final int ENDBR = 10;
  public static final int COMMA = 14;
  public static final int MULT = 27;
  public static final int EOF = 0;
  public static final int DIV = 26;
  public static final int FALSE = 31;
  public static final int GOE = 20;
  public static final int CONST = 29;
  public static final int error = 1;
  public static final int LET = 2;
  public static final int ASSIGN = 15;
  public static final int MIN = 25;
  public static final int EQEQ = 16;
  public static final int NEQ = 17;
}

